name: ValidateMetadata

permissions:
  contents: read

on:
    push:
        branches: [main]
        paths:
          - 'bdf.yml'
          - '.github/workflows/validate_metadata.yml'
    pull_request:
        branches: [main]
        paths:
          - 'bdf.yml'
          - '.github/workflows/validate_metadata.yml'

jobs:
    validate-all-performer-tools:
        uses: ARPA-H-BDF/bdfkb-schema/.github/workflows/ci-validate.yaml@main
        with:
            python-version: '3.11'